- hosts: all
  vars_files:
    - vault.yml
  tasks: 
  - community.docker.docker_container:
      name: app
      image: "shlyapnikovan/rails-project-lvl2:{{ version }}"
      restart_policy: always
      state: started
      ports:
        - 3000:3000
      env:
        NODE_ENV: production
        RAILS_ENV: production
        SECRET_KEY_BASE: '{{ secret_key_base }}'
    become: yes
