- hosts: all
  tasks:
  - community.docker.docker_container:
      name: app
      image: "shlyapnikovan/rails-project-lvl2:latest"
      restart_policy: always
      state: started
      ports:
        - 3000:3000
      env:
        NODE_ENV: production
        RAILS_ENV: production
        SECRET_KEY_BASE: 6e0fdbbd4d98d4db7ed74999666b10d33dd9cc1032ed4c20b8e1e198ecc4b51e85a06b0da006eecfb6980f3a1cc5f49991b127e8a800c2f15feb09518147854b
    become: yes
