name: release

on:
  create:
    tags:
      - v*

env:
  APP_IMAGE_NAME: hexletcomponents/devops-example-app

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Push images
        run: docker pull ${{ env.APP_IMAGE_NAME }}:latest

      - name: Tagging
        run: docker tag ${{ env.APP_IMAGE_NAME }}:latest ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}

      - name: Login DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image
        run: docker push ${{ env.APP_IMAGE_NAME }}:${{ github.ref_name }}
